// Generated by CoffeeScript 1.9.1
(function() {
  var TechnologyController;

  TechnologyController = (function() {
    function TechnologyController(scope, technologies, log) {
      this.scope = scope;
      this.log = log;
      this.scope.technologies = technologies;
      this.log.info("Bound " + technologies.length + " techologies to scope.");
    }

    return TechnologyController;

  })();

  angular.module("<%= name %>").controller("TechnologyController", ["$scope", "TECHNOLOGIES", "$log", TechnologyController]);

}).call(this);
